-- script para proxima migracion
DROP TABLE PDRMYE.ORG;
DROP TABLE PDRMYE.ORGDetalle;
DROP TABLE PDRMYE.ORGCfdi;
DROP TABLE PDRMYE.ORGSpei;
DROP TABLE PDRMYE.Reportes;

-- deletes
-- LIMPIAR LA TABLA ESTATUS
DELETE FROM PDRMYE.Estatus ES WHERE ES.Proceso = (SELECT id FROM PDRMYE.Procesos WHERE Nombre='DAMOP_OPERACION_ORG');
LIMPIAR LA TABLA PROCESOS
DELETE FROM PDRMYE.Procesos WHERE Nombre='DAMOP_OPERACION_ORG';

